apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
data:
  config.json: |
    {
      "message": "Hello from base",
      "database": {
        "user": "default_user",
        "password": "default_password"
      }
    }