apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config
data:
  config.json: |
    {
      "message": "Bonjour depuis Dev",
      "database": {
        "user": "admin",
        "password": "password123"
      }
    }